#!/bin/bash
#COLUMNS=
#LINES=
#(alacritty --class ranger -e ranger $@ &) > /dev/null 2>&1

COLUMNS=
LINES=
#(kitty --class ranger -e ranger $@ & ) > /dev/null 2>&1
(alacritty --class ranger -e ranger $@ & ) > /dev/null 2>&1

